### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by hashrock** [skanehira/deno-clippy#4]
how about this?

![deno-clippy](https://user-images.githubusercontent.com/3132889/185885620-1f34a8e3-5688-440c-96e5-99af87d48caa.svg)

![deno-clippy-2](https://user-images.githubusercontent.com/3132889/185892857-a153e2f3-ed11-4bcf-b864-96761b5bf451.svg)

**Comment by skanehira** [comment]
@hashrock Awesome!
I like the second log :)
Can I use this log?

**Comment by hashrock** [comment]
Yeah of course!
I'll make a PR to include this logo to README

**Comment by skanehira** [comment]
@hashrock Thank you :)
